require 'bundler/setup'
require 'rspec/core/rake_task'

desc 'Default: Run all specs for a specific rails version.'
task :default => :spec

desc "Run all specs for a specific rails version"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = defined?(SPEC) ? SPEC : ['../shared/spec/**/*_spec.rb']
end
