source 'https://rubygems.org'

gem 'sqlite3'
gem 'rails', '=6.1.2.1'
gem 'rspec'
gem 'rspec-rails'
gem 'database_cleaner'
gem 'query_diet', :path => '../..'
gem 'capybara'
# For Ruby 3.1.1
gem 'matrix'
gem 'net-smtp'
