source 'http://rubygems.org'

gem 'sqlite3'
gem 'rails', '~>5.0.0.beta2'
gem 'rspec', '3.5.0.beta1'
gem 'rspec-rails', '3.5.0.beta1'
gem 'database_cleaner'
gem 'query_diet', :path => '../..'
gem 'capybara'
