name: Tests
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy: 
      fail-fast: false
      matrix:
        include:
        - ruby: 2.3.0
        - ruby: 2.4.0
        - ruby: 2.5.0
        - ruby: 2.6.0
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install rake
      run: gem install rake
    - name: Run tests
      run: rake
