name: Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7.8
          directory: 'spec/rails-6.1'
        - ruby: 2.7.8
          directory: 'spec/rails-7.0'
        - ruby: 3.0.0
          directory: 'spec/rails-6.1'
        - ruby: 3.0.0
          directory: 'spec/rails-7.0'
        - ruby: 3.1.1
          directory: 'spec/rails-6.1'
        - ruby: 3.1.1
          directory: 'spec/rails-7.0'
        - ruby: 3.1.1
          directory: 'spec/rails-7.1'
        - ruby: 3.1.1
          directory: 'spec/rails-7.2'
        - ruby: 3.3.4
          directory: 'spec/rails-7.0'
        - ruby: 3.3.4
          directory: 'spec/rails-7.1'
        - ruby: 3.3.4
          directory: 'spec/rails-7.2'
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install bundler
      run: gem install bundler:2.4.22
    - name: Bundle
      run: bundle install
      working-directory: "${{ matrix.directory }}"
    - name: Run tests
      run: bundle exec rake spec
      working-directory: "${{ matrix.directory }}"
