name: Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.5.8
          directory: 'spec/rails-3.2'
        - ruby: 2.5.8
          directory: 'spec/rails-4.2'
        - ruby: 2.5.8
          directory: 'spec/rails-5.2'
        - ruby: 2.5.8
          directory: 'spec/rails-6.1'
        - ruby: 2.6.6
          directory: 'spec/rails-4.2'
        - ruby: 2.6.6
          directory: 'spec/rails-5.2'
        - ruby: 2.6.6
          directory: 'spec/rails-6.1'
        - ruby: 2.7.2
          directory: 'spec/rails-5.2'
        - ruby: 2.7.2
          directory: 'spec/rails-6.1'
        - ruby: 3.0.0
          directory: 'spec/rails-6.1'
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install bundler
      run: gem install bundler:1.17.3
    - name: Bundle
      run: bundle install
      working-directory: "${{ matrix.directory }}"
    - name: Run tests
      run: bundle exec rake spec
      working-directory: "${{ matrix.directory }}"
