name: Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.5.8
          gemfile: Gemfile.3.2.sqlite
        - ruby: 2.5.8
          gemfile: Gemfile.4.2.sqlite
        - ruby: 2.5.8
          gemfile: Gemfile.5.2.sqlite
        - ruby: 2.5.8
          gemfile: Gemfile.6.1.sqlite
        - ruby: 2.6.6
          gemfile: Gemfile.4.2.sqlite
        - ruby: 2.6.6
          gemfile: Gemfile.5.2.sqlite
        - ruby: 2.6.6
          gemfile: Gemfile.6.1.sqlite
        - ruby: 2.7.2
          gemfile: Gemfile.5.2.sqlite
        - ruby: 2.7.2
          gemfile: Gemfile.6.1.sqlite
        - ruby: 2.7.2
          gemfile: Gemfile.7.0.sqlite
        - ruby: 3.0.0
          gemfile: Gemfile.6.1.sqlite
        - ruby: 3.0.0
          gemfile: Gemfile.7.0.sqlite
        - ruby: 3.1.1
          gemfile: Gemfile.6.1.sqlite
        - ruby: 3.1.1
          gemfile: Gemfile.7.0.sqlite
        - ruby: 3.1.1
          gemfile: Gemfile.7.1.sqlite
        - ruby: 3.1.1
          gemfile: Gemfile.7.2.sqlite
        - ruby: 3.3.3
          gemfile: Gemfile.7.0.sqlite
        - ruby: 3.3.3
          gemfile: Gemfile.7.1.sqlite
        - ruby: 3.3.3
          gemfile: Gemfile.7.2.sqlite
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Bundle
      run: |
        gem install bundler:1.17.3
        bundle install --no-deployment
    - name: Run tests
      run: bundle exec rspec
